### ISSUE TITLE
[MRRESOURCES-47] configuration.properties results in ClassNotFoundException

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-remote-resources-plugin#107]
**[jieryn](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jieryn)** opened **[MRRESOURCES-47](https://issues.apache.org/jira/browse/MRRESOURCES-47?redirect=false)** and commented

    <execution>
      <id>dao</id>
      <goals>
        <goal>process</goal>
      </goals>
      <configuration>
        <resourceBundles>
          <resourceBundle>com.mycom.resources:dao:1.0</resourceBundle>
          
          <properties>
            <jdbc.driverClassName>${jdbc.driverClassName}</jdbc.driverClassName>
            <jdbc.url>${jdbc.url}</jdbc.url>
            <jdbc.username>${jdbc.username}</jdbc.username>
            <jdbc.password>${jdbc.password}</jdbc.password>
          </properties>
        </resourceBundles>
      </configuration>
    </execution>

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-remote-resources-plugin:1.1:process (dao) on project base: Unable to parse configuration of mojo org.apache.maven.plugins:maven-remote-resources-plugin:1.1:process: Error loading class 'org.apache.maven.plugin.resources.remote.Properties' -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-remote-resources-plugin:1.1:process (dao) on project base: Unable to parse configuration of mojo org.apache.maven.plugins:maven-remote-resources-plugin:1.1:process: Error loading class 'org.apache.maven.plugin.resources.remote.Properties'
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:574)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:317)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:247)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:104)
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:422)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:157)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:122)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:48)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)
at java.lang.reflect.Method.invoke(Method.java:600)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.PluginConfigurationException: Unable to parse configuration of mojo org.apache.maven.plugins:maven-remote-resources-plugin:1.1:process: Error loading class 'org.apache.maven.plugin.resources.remote.Properties'
at org.apache.maven.plugin.internal.DefaultMavenPluginManager.populatePluginFields(DefaultMavenPluginManager.java:656)
at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:608)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:94)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:562)
... 14 more
Caused by: org.codehaus.plexus.component.configurator.ComponentConfigurationException: Error loading class 'org.apache.maven.plugin.resources.remote.Properties'
at org.codehaus.plexus.component.configurator.converters.composite.CollectionConverter.fromConfiguration(CollectionConverter.java:171)
at org.codehaus.plexus.component.configurator.converters.ComponentValueSetter.configure(ComponentValueSetter.java:260)
at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.processConfiguration(ObjectWithFieldsConverter.java:145)
at org.codehaus.plexus.component.configurator.BasicComponentConfigurator.configureComponent(BasicComponentConfigurator.java:58)
at org.apache.maven.plugin.internal.DefaultMavenPluginManager.populatePluginFields(DefaultMavenPluginManager.java:643)
... 17 more
Caused by: java.lang.ClassNotFoundException: org.apache.maven.plugin.resources.remote.Properties
at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:244)
at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:230)
at org.codehaus.plexus.component.configurator.converters.composite.CollectionConverter.fromConfiguration(CollectionConverter.java:159)
... 21 more

---
No further details from [MRRESOURCES-47](https://issues.apache.org/jira/browse/MRRESOURCES-47?redirect=false)

**Comment by jira-importer** [comment]
**[jieryn](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jieryn)** commented

User error, I had \<properties> inside the bundle area instead of in the configuration area -- my apologies!
