### ISSUE TITLE
[MRRESOURCES-6] Remote resources are not added to test jars

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-remote-resources-plugin#114]
**[Daniel Kulp](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dkulp)** opened **[MRRESOURCES-6](https://issues.apache.org/jira/browse/MRRESOURCES-6?redirect=false)** and commented

Generated remote-resources should also be added to the test jar create with jar:test-jar.

---

**Affects:** 1.0-alpha-1

**Comment by jira-importer** [comment]
**[Stefano Bagnara](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=apache@bago.org)** commented

I think this should be done only if tests are really present.
Now there is a new bug: if the project does not have any test I have this error:

```
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] null
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.NullPointerException
        at org.apache.maven.plugin.surefire.SurefirePlugin.constructSurefireBooter(SurefirePlugin.java:594)
        at org.apache.maven.plugin.surefire.SurefirePlugin.execute(SurefirePlugin.java:391)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:443)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:539)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:480)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:459)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:311)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:278)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:143)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:334)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:125)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:272)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:585)
        at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
        at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] ------------------------------------------------------------------------
```

And this is because the NOTICE and LICENSE have been copied in the output test folder and surefire thinks there are tests to be executed!
