### ISSUE TITLE
[MRRESOURCES-15] ClassCast Exception happens when depending on the snapshot artifacts

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-remote-resources-plugin#119]
**[Balaji Mosur Ravi](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=balajimr)** opened **[MRRESOURCES-15](https://issues.apache.org/jira/browse/MRRESOURCES-15?redirect=false)** and commented

The remote resources plugin throws the following ClassCastException when there are snapshot artifacts.

INFO] ------------------------------------------------------------------------

[ERROR] FATAL ERROR

[INFO] ------------------------------------------------------------------------

[INFO] org.apache.maven.model.Repository

[INFO] ------------------------------------------------------------------------

[INFO] Trace

java.lang.ClassCastException: org.apache.maven.model.Repository

    at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetada

taManager.mergeMetadata(DefaultRepositoryMetadataManager.java:161)

    at org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetada

taManager.resolve(DefaultRepositoryMetadataManager.java:134)

    at org.apache.maven.artifact.transform.AbstractVersionTransformation.res

olveVersion(AbstractVersionTransformation.java:65)

    at org.apache.maven.artifact.transform.SnapshotTransformation.transformF

orResolve(SnapshotTransformation.java:63)

    at org.apache.maven.artifact.transform.DefaultArtifactTransformationMana

ger.transformForResolve(DefaultArtifactTransformationManager.java:43)

    at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(De

faultArtifactResolver.java:114)

    at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(De

faultArtifactResolver.java:73)

    at org.apache.maven.project.DefaultMavenProjectBuilder.findModelFromRepo

sitory(DefaultMavenProjectBuilder.java:482)

    at org.apache.maven.project.DefaultMavenProjectBuilder.assembleLineage(D

efaultMavenProjectBuilder.java:1194)

    at org.apache.maven.project.DefaultMavenProjectBuilder.buildInternal(Def

aultMavenProjectBuilder.java:697)

    at org.apache.maven.project.DefaultMavenProjectBuilder.buildFromReposito

ry(DefaultMavenProjectBuilder.java:230)

    at org.apache.maven.plugin.resources.remote.ProcessRemoteResourcesMojo.g

etProjects(ProcessRemoteResourcesMojo.java:408)

    at org.apache.maven.plugin.resources.remote.ProcessRemoteResourcesMojo.e

xecute(ProcessRemoteResourcesMojo.java:273)

    at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPlugi

nManager.java:420)

    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(Defa

ultLifecycleExecutor.java:539)

    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLi

fecycle(DefaultLifecycleExecutor.java:480)

    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(Defau

ltLifecycleExecutor.java:459)

    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHan

dleFailures(DefaultLifecycleExecutor.java:311)

    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegmen

ts(DefaultLifecycleExecutor.java:278)

    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLi

fecycleExecutor.java:143)

        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:330)
    
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:123)
    
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:272)
    
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.

java:39)

    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces

sorImpl.java:25)

        at java.lang.reflect.Method.invoke(Method.java:585)
    
        at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
    
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
    
        at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
    
    
    
        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

---

---

**Affects:** 1.0-alpha-3

**Comment by jira-importer** [comment]
**[Siveton Vincent](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=siveton)** commented

I tried to bump Doxia to the new maven-parent:pom:6 (wich uses maven-remote-resources-plugin:1.0-alpha-5) and I got this exception.

Here are the steps te reproduce it:
* bump the parent of trunks/doxia/doxia/pom.xml (r566642) and install it
* try to install sandbox/doxia/doxia-maven-plugin

**Comment by jira-importer** [comment]
**[Siveton Vincent](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=siveton)** commented

Fixed in r566658

o renamed remoteRepositories to repositories to be more clear
o added remoteArtifactRepositories field and use it, if artifact is a snapshot
