### ISSUE TITLE
[MRRESOURCES-26] NPE in remote-resources:process while sorting orgs

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-remote-resources-plugin#129]
**[Jason Dillon](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jason@planet57.com)** opened **[MRRESOURCES-26](https://issues.apache.org/jira/browse/MRRESOURCES-26?redirect=false)** and commented

For some reason I'm not quite sure of yet, when sorting orgs, the comparator will fail with a NPE due to a missing null check:

```
[INFO] ----------------------------------------------------------------------------
[INFO] Building JavaCC Maven Plugin
[INFO]    task-segment: [install]
[INFO] ----------------------------------------------------------------------------
[INFO] [enforcer:enforce {execution: default}]
[INFO] [groovy:generateStubs {execution: default}]
[INFO]  No sources found for Java stub generation
[INFO] [plugin:descriptor]
[INFO] Using 2 extractors.
[INFO] Applying extractor for language: java
[INFO] Extractor for language: java found 2 mojo descriptors.
[INFO] Applying extractor for language: bsh
[INFO] Extractor for language: bsh found 0 mojo descriptors.
[INFO] Setting property: classpath.resource.loader.class => 'org.codehaus.plexus.velocity.ContextClassLoaderResourceLoader'.
[INFO] Setting property: velocimacro.messages.on => 'false'.
[INFO] Setting property: resource.loader => 'classpath'.
[INFO] Setting property: resource.manager.logwhenfound => 'false'.
[INFO] [remote-resources:process {execution: default}]
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] null
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.NullPointerException
        at java.lang.String$CaseInsensitiveComparator.compare(String.java:1048)
        at java.lang.String$CaseInsensitiveComparator.compare(String.java:1042)
        at java.lang.String.compareToIgnoreCase(String.java:1089)
        at org.apache.maven.plugin.resources.remote.ProcessRemoteResourcesMojo$OrganizationComparator.compareStrings(ProcessRemoteResourcesMojo.java:859)
        at org.apache.maven.plugin.resources.remote.ProcessRemoteResourcesMojo$OrganizationComparator.compare(ProcessRemoteResourcesMojo.java:839)
        at java.util.TreeMap.compare(TreeMap.java:1093)
        at java.util.TreeMap.getEntry(TreeMap.java:347)
        at java.util.TreeMap.get(TreeMap.java:265)
        at org.apache.maven.plugin.resources.remote.ProcessRemoteResourcesMojo.getProjectsSortedByOrganization(ProcessRemoteResourcesMojo.java:420)
        at org.apache.maven.plugin.resources.remote.ProcessRemoteResourcesMojo.configureVelocityContext(ProcessRemoteResourcesMojo.java:532)
        at org.apache.maven.plugin.resources.remote.ProcessRemoteResourcesMojo.execute(ProcessRemoteResourcesMojo.java:305)
        at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:443)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:539)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:480)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:459)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:311)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:278)
        at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:143)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:334)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:125)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:280)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:585)
        at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
        at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
        at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
```

---

**Affects:** 1.0-alpha-6

**Attachments:**
- [MRRESOURCES-26.diff](https://issues.apache.org/jira/secure/attachment/12718317/MRRESOURCES-26.diff) (_1.13 kB_)

**Comment by jira-importer** [comment]
**[Jason Dillon](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jason@planet57.com)** commented

Attached is a patch which performs a missing null check when first arg is not null, but second arg is.

**Comment by jira-importer** [comment]
**[Jason Dillon](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jason@planet57.com)** commented

Is this snap published?  Can we get a release soon plz?
