### ISSUE TITLE
[MRRESOURCES-4] If not resourceBundles specified (or element miss-spelled) you get a NullPointerException

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-remote-resources-plugin#90]
**[Daniel Kulp](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dkulp)** opened **[MRRESOURCES-4](https://issues.apache.org/jira/browse/MRRESOURCES-4?redirect=false)** and commented

If I miss-spell the resoruceBundles config element (or forget to add one), I get:

java.lang.NullPointerException
at org.apache.maven.plugin.resources.remote.ProcessRemoteResourcesMojo.execute(ProcessRemoteResourcesMojo.java:148)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:420)
....

instead of a useful error message.

---
No further details from [MRRESOURCES-4](https://issues.apache.org/jira/browse/MRRESOURCES-4?redirect=false)

**Comment by jira-importer** [comment]
**[Daniel Kulp](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dkulp)** commented

Fixed in the sandbox at: https://svn.apache.org/repos/asf/maven/sandbox/plugins/maven-remote-resources-plugin

Just added `@required` to the resourceBundles property.

**Comment by jira-importer** [comment]
**[Daniel Kulp](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dkulp)** commented

Fixed in 505412
